#!/usr/bin/env bash
# shellcheck disable=SC2086
# the mighty pocket protector,
#   Copyright 2025 Anders F Björklund
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

NERDCTL=${NERDCTL:-nerdctl}
TOOLBOX=${TOOLBOX:-nerdbox}
DISTRO=${DISTRO:-debian}
distro=$(dirname $0)/templates/$DISTRO
image=localhost/$DISTRO-$TOOLBOX-$USER

uid=$(id -u)
gid=$(id -g | sed -e 's/20/1000/') # dialout group
user=$USER
home=/home/$USER.linux
shell=/bin/bash
volumes="-v $TOOLBOX:$home -v /tmp/lima:/tmp/lima"

cmd=$1
if [ -z $cmd ]; then
  echo "Usage: $(basename $0) build | create | list | remove | run | setup | shell"
  exit 1
fi
shift
case $cmd in
  setup)
    uid=$uid gid=$gid user=$user home=$home shell=$shell envsubst <$distro/Containerfile.in >Containerfile
    cp $distro/ufetch.sh .
    ;;
  build)
    $NERDCTL build -t $image .
    ;;
  ls|list)
    $NERDCTL container ls --filter name=$TOOLBOX; echo
    $NERDCTL images $image; echo
    ;;
  create)
    $NERDCTL create $volumes --name $TOOLBOX --hostname $TOOLBOX --init $image sleep infinity | cut -c1-12
    $NERDCTL start $TOOLBOX >/dev/null
    ;;
  enter|shell)
    $NERDCTL exec -u $uid:$gid -e TERM -e COLORTERM -it $TOOLBOX "${@:-$shell}"
    ;;
  rm|remove)
    $NERDCTL stop $TOOLBOX >/dev/null
    $NERDCTL rm $TOOLBOX 
    ;;
  run)
    $NERDCTL run $volumes --rm -u $uid:$gid -e TERM -e COLORTERM -it $image "${@:-$shell}"
    ;;
  *)
    echo "Unknown command: $cmd" >&2
    exit 255
    ;;
esac
