FROM docker.io/library/debian:latest
RUN apt-get update && apt-get install -y procps psmisc && rm -rf /var/lib/apt/lists/* 
ADD ufetch.sh /usr/local/bin/ufetch

RUN groupadd -g $gid $group && useradd -u $uid -g $gid -d $home -s $shell -m -N $user
VOLUME $home
WORKDIR $home
USER $user
CMD ["$shell"]
