FROM docker.io/library/ubuntu:latest
RUN apt-get update && apt-get install -y procps psmisc && rm -rf /var/lib/apt/lists/* \
&& userdel --remove ubuntu
ADD ufetch.sh /usr/local/bin/ufetch

RUN groupadd -g $gid $user && useradd -u $uid -g $gid -d $home -s $shell -m -N $user \
&& rm -f /etc/.pwd.lock
VOLUME $home
WORKDIR $home
USER $user
CMD ["$shell"]
