FROM docker.io/library/ubuntu:latest
RUN userdel --remove ubuntu

RUN groupadd -g $gid anders && useradd -u $uid -g $gid -d $home -s $shell -m -N $user \
&& rm -f /etc/.pwd.lock
VOLUME $home
WORKDIR $home
USER $user
CMD ["$shell"]
